version: "3.7"

services:
  pokemon-game-app:
    container_name: pokemonGameApp
    build:
      context: .
      dockerfile: dockerfile
    command: sh /var/www/html/node_start.sh
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:8080

    working_dir: /var/www/html
#     networks:
#       - mysql_net
# networks:
#   mysql_net:
#     external: true
#     name: mysql_net

